### ISSUE TITLE
Migration to version 9.0

### ISSUE THREAD

**Issue by pedrobaeza** [serviciosbaeza/serviciosbaeza-odoo-addons#19]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-9.0
# Modules to migrate
- [ ] account_balance_reporting_budget
- [ ] product_supplierinfo_variant
- [ ] stock_valued_picking_report
- [ ] purchase_order_precreate_analytic
- [ ] project_task_work_print
- [ ] account_periodical_invoicing
- [ ] project_work_time_control
- [ ] website_favicon
- [ ] sale_recurring_orders

**Comment by flotho** [comment]
Great, I'll push the supplierinfo_variant soon
